services:
  db:
    extends:
      file: docker-compose.yml
      service: db

  backend:
    image: ghcr.io/tomatoinoil/wallet-backend-test:prod
    extends:
      file: docker-compose.yml
      service: backend
    depends_on:
      - db

  nginx:
    extends:
      file: docker-compose.yml
      service: nginx
    volumes:
      - ./default.prod.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  data_value:
