# Кэш Python
**/__pycache__/
*.py[cod]
*$py.class

# Логи и временные файлы
*.log
*.tmp
*.bak

# Тестовые и документационные файлы
**/tests/
**/docs/

# Статика и медиа
**/static/
**/media/
**/uploads/

# БД, используемая при локальном запуске проекта
**/db.sqlite3
